# Generated by Django 2.1.5 on 2019-01-15 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_title', models.CharField(max_length=100)),
                ('game_state', models.TextField()),
                ('Player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_is_host', to=settings.AUTH_USER_MODEL)),
                ('Player_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='_is_Guest', to=settings.AUTH_USER_MODEL)),
                ('active_player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='_is_active', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
