# Generated by Django 2.1.5 on 2019-01-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190116_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='Game_title',
            new_name='game_title',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='Player_1',
            new_name='player_1',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='Player_2',
            new_name='player_2',
        ),
    ]
